"""add version column to inventory_items

Revision ID: 9e5807408b22
Revises: fc65c5fdb934
Create Date: 2026-04-24 00:50:47.151706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e5807408b22'
down_revision: Union[str, Sequence[str], None] = 'fc65c5fdb934'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add with a server default so existing rows get version=0 immediately.
    # Then drop the server default so future inserts must supply the value
    # explicitly (the ORM model default handles that).
    op.add_column('inventory_items', sa.Column(
        'version', sa.Integer(), nullable=False, server_default='0'
    ))
    op.alter_column('inventory_items', 'version', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory_items', 'version')
    # ### end Alembic commands ###
